spring.datasource.url=jdbc:postgresql://localhost:5432/techstore
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# URL de la cola de AWS SQS (Asegúrate de cambiar los números por tu ID de cuenta real de AWS Academy al crearla)
aws.sqs.queue-url=https://sqs.us-east-1.amazonaws.com/123456789012/techstore-audit-queue

# Credenciales para el inicio de sesión en la API (Spring Security)
spring.security.user.name=usuario_api
spring.security.user.password=secreto123